# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ManualStationService_pb2 as ManualStationService__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ManualStationService_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ManualStationServiceStub(object):
    """=============================================================================
    Manual Station Service
    =============================================================================
    Virtual station for operator interactions in automated workflows.
    Handles manual tasks, notifications, and confirmations.

    ═══════════════════════════════════════════════════════════════════════
    OBSERVABLE PROPERTIES
    ═══════════════════════════════════════════════════════════════════════
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetStationStatus = channel.unary_unary(
                '/it.chemlab.manualstation.ManualStationService/GetStationStatus',
                request_serializer=ManualStationService__pb2.GetStationStatusRequest.SerializeToString,
                response_deserializer=ManualStationService__pb2.GetStationStatusResponse.FromString,
                _registered_method=True)
        self.SubscribeStationStatus = channel.unary_stream(
                '/it.chemlab.manualstation.ManualStationService/SubscribeStationStatus',
                request_serializer=ManualStationService__pb2.SubscribeStationStatusRequest.SerializeToString,
                response_deserializer=ManualStationService__pb2.GetStationStatusResponse.FromString,
                _registered_method=True)
        self.GetPendingTaskCount = channel.unary_unary(
                '/it.chemlab.manualstation.ManualStationService/GetPendingTaskCount',
                request_serializer=ManualStationService__pb2.GetPendingTaskCountRequest.SerializeToString,
                response_deserializer=ManualStationService__pb2.GetPendingTaskCountResponse.FromString,
                _registered_method=True)
        self.SubscribePendingTaskCount = channel.unary_stream(
                '/it.chemlab.manualstation.ManualStationService/SubscribePendingTaskCount',
                request_serializer=ManualStationService__pb2.SubscribePendingTaskCountRequest.SerializeToString,
                response_deserializer=ManualStationService__pb2.GetPendingTaskCountResponse.FromString,
                _registered_method=True)
        self.GetLastNotification = channel.unary_unary(
                '/it.chemlab.manualstation.ManualStationService/GetLastNotification',
                request_serializer=ManualStationService__pb2.GetLastNotificationRequest.SerializeToString,
                response_deserializer=ManualStationService__pb2.GetLastNotificationResponse.FromString,
                _registered_method=True)
        self.SubscribeLastNotification = channel.unary_stream(
                '/it.chemlab.manualstation.ManualStationService/SubscribeLastNotification',
                request_serializer=ManualStationService__pb2.SubscribeLastNotificationRequest.SerializeToString,
                response_deserializer=ManualStationService__pb2.GetLastNotificationResponse.FromString,
                _registered_method=True)
        self.RequestOperatorTask = channel.unary_stream(
                '/it.chemlab.manualstation.ManualStationService/RequestOperatorTask',
                request_serializer=ManualStationService__pb2.RequestOperatorTaskRequest.SerializeToString,
                response_deserializer=ManualStationService__pb2.RequestOperatorTaskResponse.FromString,
                _registered_method=True)
        self.ConfirmTaskComplete = channel.unary_unary(
                '/it.chemlab.manualstation.ManualStationService/ConfirmTaskComplete',
                request_serializer=ManualStationService__pb2.ConfirmTaskCompleteRequest.SerializeToString,
                response_deserializer=ManualStationService__pb2.ConfirmTaskCompleteResponse.FromString,
                _registered_method=True)
        self.CancelTask = channel.unary_unary(
                '/it.chemlab.manualstation.ManualStationService/CancelTask',
                request_serializer=ManualStationService__pb2.CancelTaskRequest.SerializeToString,
                response_deserializer=ManualStationService__pb2.CancelTaskResponse.FromString,
                _registered_method=True)
        self.GetActiveTasks = channel.unary_unary(
                '/it.chemlab.manualstation.ManualStationService/GetActiveTasks',
                request_serializer=ManualStationService__pb2.GetActiveTasksRequest.SerializeToString,
                response_deserializer=ManualStationService__pb2.GetActiveTasksResponse.FromString,
                _registered_method=True)
        self.GetTaskHistory = channel.unary_unary(
                '/it.chemlab.manualstation.ManualStationService/GetTaskHistory',
                request_serializer=ManualStationService__pb2.GetTaskHistoryRequest.SerializeToString,
                response_deserializer=ManualStationService__pb2.GetTaskHistoryResponse.FromString,
                _registered_method=True)
        self.SendNotification = channel.unary_unary(
                '/it.chemlab.manualstation.ManualStationService/SendNotification',
                request_serializer=ManualStationService__pb2.SendNotificationRequest.SerializeToString,
                response_deserializer=ManualStationService__pb2.SendNotificationResponse.FromString,
                _registered_method=True)


class ManualStationServiceServicer(object):
    """=============================================================================
    Manual Station Service
    =============================================================================
    Virtual station for operator interactions in automated workflows.
    Handles manual tasks, notifications, and confirmations.

    ═══════════════════════════════════════════════════════════════════════
    OBSERVABLE PROPERTIES
    ═══════════════════════════════════════════════════════════════════════
    """

    def GetStationStatus(self, request, context):
        """Station status (idle, waiting_for_operator, busy)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeStationStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPendingTaskCount(self, request, context):
        """Pending task count
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribePendingTaskCount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLastNotification(self, request, context):
        """Last notification
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeLastNotification(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestOperatorTask(self, request, context):
        """═══════════════════════════════════════════════════════════════════════
        COMMANDS
        ═══════════════════════════════════════════════════════════════════════

        Request operator task (blocking until confirmed or timeout)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfirmTaskComplete(self, request, context):
        """Confirm task completed
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelTask(self, request, context):
        """Cancel a pending task
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetActiveTasks(self, request, context):
        """Get active tasks
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTaskHistory(self, request, context):
        """Get task history
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendNotification(self, request, context):
        """Send notification (non-blocking)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ManualStationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetStationStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStationStatus,
                    request_deserializer=ManualStationService__pb2.GetStationStatusRequest.FromString,
                    response_serializer=ManualStationService__pb2.GetStationStatusResponse.SerializeToString,
            ),
            'SubscribeStationStatus': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeStationStatus,
                    request_deserializer=ManualStationService__pb2.SubscribeStationStatusRequest.FromString,
                    response_serializer=ManualStationService__pb2.GetStationStatusResponse.SerializeToString,
            ),
            'GetPendingTaskCount': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPendingTaskCount,
                    request_deserializer=ManualStationService__pb2.GetPendingTaskCountRequest.FromString,
                    response_serializer=ManualStationService__pb2.GetPendingTaskCountResponse.SerializeToString,
            ),
            'SubscribePendingTaskCount': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribePendingTaskCount,
                    request_deserializer=ManualStationService__pb2.SubscribePendingTaskCountRequest.FromString,
                    response_serializer=ManualStationService__pb2.GetPendingTaskCountResponse.SerializeToString,
            ),
            'GetLastNotification': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLastNotification,
                    request_deserializer=ManualStationService__pb2.GetLastNotificationRequest.FromString,
                    response_serializer=ManualStationService__pb2.GetLastNotificationResponse.SerializeToString,
            ),
            'SubscribeLastNotification': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeLastNotification,
                    request_deserializer=ManualStationService__pb2.SubscribeLastNotificationRequest.FromString,
                    response_serializer=ManualStationService__pb2.GetLastNotificationResponse.SerializeToString,
            ),
            'RequestOperatorTask': grpc.unary_stream_rpc_method_handler(
                    servicer.RequestOperatorTask,
                    request_deserializer=ManualStationService__pb2.RequestOperatorTaskRequest.FromString,
                    response_serializer=ManualStationService__pb2.RequestOperatorTaskResponse.SerializeToString,
            ),
            'ConfirmTaskComplete': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfirmTaskComplete,
                    request_deserializer=ManualStationService__pb2.ConfirmTaskCompleteRequest.FromString,
                    response_serializer=ManualStationService__pb2.ConfirmTaskCompleteResponse.SerializeToString,
            ),
            'CancelTask': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelTask,
                    request_deserializer=ManualStationService__pb2.CancelTaskRequest.FromString,
                    response_serializer=ManualStationService__pb2.CancelTaskResponse.SerializeToString,
            ),
            'GetActiveTasks': grpc.unary_unary_rpc_method_handler(
                    servicer.GetActiveTasks,
                    request_deserializer=ManualStationService__pb2.GetActiveTasksRequest.FromString,
                    response_serializer=ManualStationService__pb2.GetActiveTasksResponse.SerializeToString,
            ),
            'GetTaskHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTaskHistory,
                    request_deserializer=ManualStationService__pb2.GetTaskHistoryRequest.FromString,
                    response_serializer=ManualStationService__pb2.GetTaskHistoryResponse.SerializeToString,
            ),
            'SendNotification': grpc.unary_unary_rpc_method_handler(
                    servicer.SendNotification,
                    request_deserializer=ManualStationService__pb2.SendNotificationRequest.FromString,
                    response_serializer=ManualStationService__pb2.SendNotificationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'it.chemlab.manualstation.ManualStationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('it.chemlab.manualstation.ManualStationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ManualStationService(object):
    """=============================================================================
    Manual Station Service
    =============================================================================
    Virtual station for operator interactions in automated workflows.
    Handles manual tasks, notifications, and confirmations.

    ═══════════════════════════════════════════════════════════════════════
    OBSERVABLE PROPERTIES
    ═══════════════════════════════════════════════════════════════════════
    """

    @staticmethod
    def GetStationStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/it.chemlab.manualstation.ManualStationService/GetStationStatus',
            ManualStationService__pb2.GetStationStatusRequest.SerializeToString,
            ManualStationService__pb2.GetStationStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeStationStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/it.chemlab.manualstation.ManualStationService/SubscribeStationStatus',
            ManualStationService__pb2.SubscribeStationStatusRequest.SerializeToString,
            ManualStationService__pb2.GetStationStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPendingTaskCount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/it.chemlab.manualstation.ManualStationService/GetPendingTaskCount',
            ManualStationService__pb2.GetPendingTaskCountRequest.SerializeToString,
            ManualStationService__pb2.GetPendingTaskCountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribePendingTaskCount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/it.chemlab.manualstation.ManualStationService/SubscribePendingTaskCount',
            ManualStationService__pb2.SubscribePendingTaskCountRequest.SerializeToString,
            ManualStationService__pb2.GetPendingTaskCountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLastNotification(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/it.chemlab.manualstation.ManualStationService/GetLastNotification',
            ManualStationService__pb2.GetLastNotificationRequest.SerializeToString,
            ManualStationService__pb2.GetLastNotificationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeLastNotification(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/it.chemlab.manualstation.ManualStationService/SubscribeLastNotification',
            ManualStationService__pb2.SubscribeLastNotificationRequest.SerializeToString,
            ManualStationService__pb2.GetLastNotificationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestOperatorTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/it.chemlab.manualstation.ManualStationService/RequestOperatorTask',
            ManualStationService__pb2.RequestOperatorTaskRequest.SerializeToString,
            ManualStationService__pb2.RequestOperatorTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConfirmTaskComplete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/it.chemlab.manualstation.ManualStationService/ConfirmTaskComplete',
            ManualStationService__pb2.ConfirmTaskCompleteRequest.SerializeToString,
            ManualStationService__pb2.ConfirmTaskCompleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/it.chemlab.manualstation.ManualStationService/CancelTask',
            ManualStationService__pb2.CancelTaskRequest.SerializeToString,
            ManualStationService__pb2.CancelTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetActiveTasks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/it.chemlab.manualstation.ManualStationService/GetActiveTasks',
            ManualStationService__pb2.GetActiveTasksRequest.SerializeToString,
            ManualStationService__pb2.GetActiveTasksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTaskHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/it.chemlab.manualstation.ManualStationService/GetTaskHistory',
            ManualStationService__pb2.GetTaskHistoryRequest.SerializeToString,
            ManualStationService__pb2.GetTaskHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendNotification(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/it.chemlab.manualstation.ManualStationService/SendNotification',
            ManualStationService__pb2.SendNotificationRequest.SerializeToString,
            ManualStationService__pb2.SendNotificationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
