# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import OpentronsService_pb2 as OpentronsService__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in OpentronsService_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OpentronsServiceStub(object):
    """═══════════════════════════════════════════════════════════════════════════
    OPENTRONS FLEX SERVICE - WORKFLOW API
    ═══════════════════════════════════════════════════════════════════════════

    This simplified interface focuses on workflow-level operations:
    1. Robot Control     - Initialize, Home, Emergency Stop
    2. HAL Configuration - Load hardware abstraction layer configs  
    3. Recipe Execution  - Select and run JSON recipes
    4. Tip Management    - Refill and track tip usage
    5. Monitoring        - Status, info, modules

    Low-level liquid handling (Transfer, Aspirate, etc.) is handled
    internally by recipes via the UNIVERSAL_TEMPLATE protocol generator.
    ═══════════════════════════════════════════════════════════════════════════

    ─────────────────────────────────────────────────────────────────────
    ROBOT CONTROL
    ─────────────────────────────────────────────────────────────────────
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Initialize = channel.unary_unary(
                '/it.chemlab.opentrons.OpentronsService/Initialize',
                request_serializer=OpentronsService__pb2.InitializeRequest.SerializeToString,
                response_deserializer=OpentronsService__pb2.InitializeResponse.FromString,
                _registered_method=True)
        self.Home = channel.unary_stream(
                '/it.chemlab.opentrons.OpentronsService/Home',
                request_serializer=OpentronsService__pb2.HomeRequest.SerializeToString,
                response_deserializer=OpentronsService__pb2.HomeResponse.FromString,
                _registered_method=True)
        self.EmergencyStop = channel.unary_unary(
                '/it.chemlab.opentrons.OpentronsService/EmergencyStop',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=OpentronsService__pb2.EmergencyStopResponse.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/it.chemlab.opentrons.OpentronsService/GetStatus',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=OpentronsService__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.ListHardwareConfigs = channel.unary_unary(
                '/it.chemlab.opentrons.OpentronsService/ListHardwareConfigs',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=OpentronsService__pb2.ListHardwareConfigsResponse.FromString,
                _registered_method=True)
        self.LoadHardwareConfig = channel.unary_unary(
                '/it.chemlab.opentrons.OpentronsService/LoadHardwareConfig',
                request_serializer=OpentronsService__pb2.LoadHardwareConfigRequest.SerializeToString,
                response_deserializer=OpentronsService__pb2.LoadHardwareConfigResponse.FromString,
                _registered_method=True)
        self.GetCurrentConfig = channel.unary_unary(
                '/it.chemlab.opentrons.OpentronsService/GetCurrentConfig',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=OpentronsService__pb2.GetCurrentConfigResponse.FromString,
                _registered_method=True)
        self.ListRecipes = channel.unary_unary(
                '/it.chemlab.opentrons.OpentronsService/ListRecipes',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=OpentronsService__pb2.ListRecipesResponse.FromString,
                _registered_method=True)
        self.ExecuteRecipe = channel.unary_stream(
                '/it.chemlab.opentrons.OpentronsService/ExecuteRecipe',
                request_serializer=OpentronsService__pb2.ExecuteRecipeRequest.SerializeToString,
                response_deserializer=OpentronsService__pb2.ExecuteRecipeResponse.FromString,
                _registered_method=True)
        self.PauseRun = channel.unary_unary(
                '/it.chemlab.opentrons.OpentronsService/PauseRun',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=OpentronsService__pb2.PauseRunResponse.FromString,
                _registered_method=True)
        self.ResumeRun = channel.unary_unary(
                '/it.chemlab.opentrons.OpentronsService/ResumeRun',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=OpentronsService__pb2.ResumeRunResponse.FromString,
                _registered_method=True)
        self.AbortRun = channel.unary_unary(
                '/it.chemlab.opentrons.OpentronsService/AbortRun',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=OpentronsService__pb2.AbortRunResponse.FromString,
                _registered_method=True)
        self.ListTipRacks = channel.unary_unary(
                '/it.chemlab.opentrons.OpentronsService/ListTipRacks',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=OpentronsService__pb2.ListTipRacksResponse.FromString,
                _registered_method=True)
        self.RefillTipRack = channel.unary_unary(
                '/it.chemlab.opentrons.OpentronsService/RefillTipRack',
                request_serializer=OpentronsService__pb2.RefillTipRackRequest.SerializeToString,
                response_deserializer=OpentronsService__pb2.RefillTipRackResponse.FromString,
                _registered_method=True)
        self.ResetTipTracking = channel.unary_unary(
                '/it.chemlab.opentrons.OpentronsService/ResetTipTracking',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=OpentronsService__pb2.ResetTipTrackingResponse.FromString,
                _registered_method=True)
        self.SetLights = channel.unary_unary(
                '/it.chemlab.opentrons.OpentronsService/SetLights',
                request_serializer=OpentronsService__pb2.SetLightsRequest.SerializeToString,
                response_deserializer=OpentronsService__pb2.SetLightsResponse.FromString,
                _registered_method=True)
        self.GetRobotInfo = channel.unary_unary(
                '/it.chemlab.opentrons.OpentronsService/GetRobotInfo',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=OpentronsService__pb2.RobotInfoResponse.FromString,
                _registered_method=True)
        self.GetModulesStatus = channel.unary_unary(
                '/it.chemlab.opentrons.OpentronsService/GetModulesStatus',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=OpentronsService__pb2.ModulesStatusResponse.FromString,
                _registered_method=True)
        self.SubscribeStatus = channel.unary_stream(
                '/it.chemlab.opentrons.OpentronsService/SubscribeStatus',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=OpentronsService__pb2.StatusResponse.FromString,
                _registered_method=True)


class OpentronsServiceServicer(object):
    """═══════════════════════════════════════════════════════════════════════════
    OPENTRONS FLEX SERVICE - WORKFLOW API
    ═══════════════════════════════════════════════════════════════════════════

    This simplified interface focuses on workflow-level operations:
    1. Robot Control     - Initialize, Home, Emergency Stop
    2. HAL Configuration - Load hardware abstraction layer configs  
    3. Recipe Execution  - Select and run JSON recipes
    4. Tip Management    - Refill and track tip usage
    5. Monitoring        - Status, info, modules

    Low-level liquid handling (Transfer, Aspirate, etc.) is handled
    internally by recipes via the UNIVERSAL_TEMPLATE protocol generator.
    ═══════════════════════════════════════════════════════════════════════════

    ─────────────────────────────────────────────────────────────────────
    ROBOT CONTROL
    ─────────────────────────────────────────────────────────────────────
    """

    def Initialize(self, request, context):
        """Initialize connection to the robot
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Home(self, request, context):
        """Home all axes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EmergencyStop(self, request, context):
        """Emergency stop - immediately halt all operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Get current robot status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListHardwareConfigs(self, request, context):
        """─────────────────────────────────────────────────────────────────────
        HAL CONFIGURATION
        ─────────────────────────────────────────────────────────────────────

        List available hardware configurations (from Library/HardwareConfig)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadHardwareConfig(self, request, context):
        """Load a hardware configuration (HAL)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCurrentConfig(self, request, context):
        """Get currently loaded hardware configuration
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRecipes(self, request, context):
        """─────────────────────────────────────────────────────────────────────
        RECIPE EXECUTION
        ─────────────────────────────────────────────────────────────────────

        List available recipes (from Library/Recipes)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteRecipe(self, request, context):
        """Execute a recipe by filename - streams progress updates
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PauseRun(self, request, context):
        """Pause currently running recipe
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResumeRun(self, request, context):
        """Resume paused recipe
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AbortRun(self, request, context):
        """Abort current recipe execution
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTipRacks(self, request, context):
        """─────────────────────────────────────────────────────────────────────
        TIP MANAGEMENT
        ─────────────────────────────────────────────────────────────────────

        List tip racks with usage statistics
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefillTipRack(self, request, context):
        """Refill a tip rack (reset tip count to full)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetTipTracking(self, request, context):
        """Reset all tip tracking (after manual refill of all racks)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetLights(self, request, context):
        """─────────────────────────────────────────────────────────────────────
        MONITORING & ACCESSORIES
        ─────────────────────────────────────────────────────────────────────

        Set robot deck lights on/off
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRobotInfo(self, request, context):
        """Get robot information (model, serial, firmware)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModulesStatus(self, request, context):
        """Get status of all attached modules
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeStatus(self, request, context):
        """Subscribe to status updates (streaming)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OpentronsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Initialize': grpc.unary_unary_rpc_method_handler(
                    servicer.Initialize,
                    request_deserializer=OpentronsService__pb2.InitializeRequest.FromString,
                    response_serializer=OpentronsService__pb2.InitializeResponse.SerializeToString,
            ),
            'Home': grpc.unary_stream_rpc_method_handler(
                    servicer.Home,
                    request_deserializer=OpentronsService__pb2.HomeRequest.FromString,
                    response_serializer=OpentronsService__pb2.HomeResponse.SerializeToString,
            ),
            'EmergencyStop': grpc.unary_unary_rpc_method_handler(
                    servicer.EmergencyStop,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=OpentronsService__pb2.EmergencyStopResponse.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=OpentronsService__pb2.StatusResponse.SerializeToString,
            ),
            'ListHardwareConfigs': grpc.unary_unary_rpc_method_handler(
                    servicer.ListHardwareConfigs,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=OpentronsService__pb2.ListHardwareConfigsResponse.SerializeToString,
            ),
            'LoadHardwareConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadHardwareConfig,
                    request_deserializer=OpentronsService__pb2.LoadHardwareConfigRequest.FromString,
                    response_serializer=OpentronsService__pb2.LoadHardwareConfigResponse.SerializeToString,
            ),
            'GetCurrentConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCurrentConfig,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=OpentronsService__pb2.GetCurrentConfigResponse.SerializeToString,
            ),
            'ListRecipes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRecipes,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=OpentronsService__pb2.ListRecipesResponse.SerializeToString,
            ),
            'ExecuteRecipe': grpc.unary_stream_rpc_method_handler(
                    servicer.ExecuteRecipe,
                    request_deserializer=OpentronsService__pb2.ExecuteRecipeRequest.FromString,
                    response_serializer=OpentronsService__pb2.ExecuteRecipeResponse.SerializeToString,
            ),
            'PauseRun': grpc.unary_unary_rpc_method_handler(
                    servicer.PauseRun,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=OpentronsService__pb2.PauseRunResponse.SerializeToString,
            ),
            'ResumeRun': grpc.unary_unary_rpc_method_handler(
                    servicer.ResumeRun,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=OpentronsService__pb2.ResumeRunResponse.SerializeToString,
            ),
            'AbortRun': grpc.unary_unary_rpc_method_handler(
                    servicer.AbortRun,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=OpentronsService__pb2.AbortRunResponse.SerializeToString,
            ),
            'ListTipRacks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTipRacks,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=OpentronsService__pb2.ListTipRacksResponse.SerializeToString,
            ),
            'RefillTipRack': grpc.unary_unary_rpc_method_handler(
                    servicer.RefillTipRack,
                    request_deserializer=OpentronsService__pb2.RefillTipRackRequest.FromString,
                    response_serializer=OpentronsService__pb2.RefillTipRackResponse.SerializeToString,
            ),
            'ResetTipTracking': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetTipTracking,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=OpentronsService__pb2.ResetTipTrackingResponse.SerializeToString,
            ),
            'SetLights': grpc.unary_unary_rpc_method_handler(
                    servicer.SetLights,
                    request_deserializer=OpentronsService__pb2.SetLightsRequest.FromString,
                    response_serializer=OpentronsService__pb2.SetLightsResponse.SerializeToString,
            ),
            'GetRobotInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRobotInfo,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=OpentronsService__pb2.RobotInfoResponse.SerializeToString,
            ),
            'GetModulesStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModulesStatus,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=OpentronsService__pb2.ModulesStatusResponse.SerializeToString,
            ),
            'SubscribeStatus': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeStatus,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=OpentronsService__pb2.StatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'it.chemlab.opentrons.OpentronsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('it.chemlab.opentrons.OpentronsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OpentronsService(object):
    """═══════════════════════════════════════════════════════════════════════════
    OPENTRONS FLEX SERVICE - WORKFLOW API
    ═══════════════════════════════════════════════════════════════════════════

    This simplified interface focuses on workflow-level operations:
    1. Robot Control     - Initialize, Home, Emergency Stop
    2. HAL Configuration - Load hardware abstraction layer configs  
    3. Recipe Execution  - Select and run JSON recipes
    4. Tip Management    - Refill and track tip usage
    5. Monitoring        - Status, info, modules

    Low-level liquid handling (Transfer, Aspirate, etc.) is handled
    internally by recipes via the UNIVERSAL_TEMPLATE protocol generator.
    ═══════════════════════════════════════════════════════════════════════════

    ─────────────────────────────────────────────────────────────────────
    ROBOT CONTROL
    ─────────────────────────────────────────────────────────────────────
    """

    @staticmethod
    def Initialize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/it.chemlab.opentrons.OpentronsService/Initialize',
            OpentronsService__pb2.InitializeRequest.SerializeToString,
            OpentronsService__pb2.InitializeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Home(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/it.chemlab.opentrons.OpentronsService/Home',
            OpentronsService__pb2.HomeRequest.SerializeToString,
            OpentronsService__pb2.HomeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EmergencyStop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/it.chemlab.opentrons.OpentronsService/EmergencyStop',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            OpentronsService__pb2.EmergencyStopResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/it.chemlab.opentrons.OpentronsService/GetStatus',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            OpentronsService__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListHardwareConfigs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/it.chemlab.opentrons.OpentronsService/ListHardwareConfigs',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            OpentronsService__pb2.ListHardwareConfigsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadHardwareConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/it.chemlab.opentrons.OpentronsService/LoadHardwareConfig',
            OpentronsService__pb2.LoadHardwareConfigRequest.SerializeToString,
            OpentronsService__pb2.LoadHardwareConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCurrentConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/it.chemlab.opentrons.OpentronsService/GetCurrentConfig',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            OpentronsService__pb2.GetCurrentConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRecipes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/it.chemlab.opentrons.OpentronsService/ListRecipes',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            OpentronsService__pb2.ListRecipesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteRecipe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/it.chemlab.opentrons.OpentronsService/ExecuteRecipe',
            OpentronsService__pb2.ExecuteRecipeRequest.SerializeToString,
            OpentronsService__pb2.ExecuteRecipeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PauseRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/it.chemlab.opentrons.OpentronsService/PauseRun',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            OpentronsService__pb2.PauseRunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResumeRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/it.chemlab.opentrons.OpentronsService/ResumeRun',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            OpentronsService__pb2.ResumeRunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AbortRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/it.chemlab.opentrons.OpentronsService/AbortRun',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            OpentronsService__pb2.AbortRunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTipRacks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/it.chemlab.opentrons.OpentronsService/ListTipRacks',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            OpentronsService__pb2.ListTipRacksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RefillTipRack(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/it.chemlab.opentrons.OpentronsService/RefillTipRack',
            OpentronsService__pb2.RefillTipRackRequest.SerializeToString,
            OpentronsService__pb2.RefillTipRackResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResetTipTracking(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/it.chemlab.opentrons.OpentronsService/ResetTipTracking',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            OpentronsService__pb2.ResetTipTrackingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetLights(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/it.chemlab.opentrons.OpentronsService/SetLights',
            OpentronsService__pb2.SetLightsRequest.SerializeToString,
            OpentronsService__pb2.SetLightsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRobotInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/it.chemlab.opentrons.OpentronsService/GetRobotInfo',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            OpentronsService__pb2.RobotInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetModulesStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/it.chemlab.opentrons.OpentronsService/GetModulesStatus',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            OpentronsService__pb2.ModulesStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/it.chemlab.opentrons.OpentronsService/SubscribeStatus',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            OpentronsService__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
