# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import SiLA2Common_pb2 as SiLA2Common__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in SiLA2Common_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SiLA2ServerInfoStub(object):
    """=============================================================================
    SERVER INFO SERVICE
    =============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetServerInfo = channel.unary_unary(
                '/sila2.org.silastandard.SiLA2ServerInfo/GetServerInfo',
                request_serializer=SiLA2Common__pb2.GetServerInfoRequest.SerializeToString,
                response_deserializer=SiLA2Common__pb2.ServerInfoResponse.FromString,
                _registered_method=True)
        self.GetFeatures = channel.unary_unary(
                '/sila2.org.silastandard.SiLA2ServerInfo/GetFeatures',
                request_serializer=SiLA2Common__pb2.GetFeaturesRequest.SerializeToString,
                response_deserializer=SiLA2Common__pb2.FeaturesResponse.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/sila2.org.silastandard.SiLA2ServerInfo/GetStatus',
                request_serializer=SiLA2Common__pb2.GetStatusRequest.SerializeToString,
                response_deserializer=SiLA2Common__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.ExecuteCommand = channel.unary_stream(
                '/sila2.org.silastandard.SiLA2ServerInfo/ExecuteCommand',
                request_serializer=SiLA2Common__pb2.ExecuteCommandRequest.SerializeToString,
                response_deserializer=SiLA2Common__pb2.ExecuteCommandResponse.FromString,
                _registered_method=True)
        self.GetProperty = channel.unary_unary(
                '/sila2.org.silastandard.SiLA2ServerInfo/GetProperty',
                request_serializer=SiLA2Common__pb2.GetPropertyRequest.SerializeToString,
                response_deserializer=SiLA2Common__pb2.PropertyResponse.FromString,
                _registered_method=True)


class SiLA2ServerInfoServicer(object):
    """=============================================================================
    SERVER INFO SERVICE
    =============================================================================

    """

    def GetServerInfo(self, request, context):
        """Get complete server metadata
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFeatures(self, request, context):
        """Get all features and their commands/properties
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Health check - is the server and hardware operational?
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteCommand(self, request, context):
        """Execute any command generically (for reflection-based clients)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProperty(self, request, context):
        """Get property value generically
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SiLA2ServerInfoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetServerInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServerInfo,
                    request_deserializer=SiLA2Common__pb2.GetServerInfoRequest.FromString,
                    response_serializer=SiLA2Common__pb2.ServerInfoResponse.SerializeToString,
            ),
            'GetFeatures': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFeatures,
                    request_deserializer=SiLA2Common__pb2.GetFeaturesRequest.FromString,
                    response_serializer=SiLA2Common__pb2.FeaturesResponse.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=SiLA2Common__pb2.GetStatusRequest.FromString,
                    response_serializer=SiLA2Common__pb2.StatusResponse.SerializeToString,
            ),
            'ExecuteCommand': grpc.unary_stream_rpc_method_handler(
                    servicer.ExecuteCommand,
                    request_deserializer=SiLA2Common__pb2.ExecuteCommandRequest.FromString,
                    response_serializer=SiLA2Common__pb2.ExecuteCommandResponse.SerializeToString,
            ),
            'GetProperty': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProperty,
                    request_deserializer=SiLA2Common__pb2.GetPropertyRequest.FromString,
                    response_serializer=SiLA2Common__pb2.PropertyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sila2.org.silastandard.SiLA2ServerInfo', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sila2.org.silastandard.SiLA2ServerInfo', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SiLA2ServerInfo(object):
    """=============================================================================
    SERVER INFO SERVICE
    =============================================================================

    """

    @staticmethod
    def GetServerInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sila2.org.silastandard.SiLA2ServerInfo/GetServerInfo',
            SiLA2Common__pb2.GetServerInfoRequest.SerializeToString,
            SiLA2Common__pb2.ServerInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFeatures(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sila2.org.silastandard.SiLA2ServerInfo/GetFeatures',
            SiLA2Common__pb2.GetFeaturesRequest.SerializeToString,
            SiLA2Common__pb2.FeaturesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sila2.org.silastandard.SiLA2ServerInfo/GetStatus',
            SiLA2Common__pb2.GetStatusRequest.SerializeToString,
            SiLA2Common__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/sila2.org.silastandard.SiLA2ServerInfo/ExecuteCommand',
            SiLA2Common__pb2.ExecuteCommandRequest.SerializeToString,
            SiLA2Common__pb2.ExecuteCommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProperty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sila2.org.silastandard.SiLA2ServerInfo/GetProperty',
            SiLA2Common__pb2.GetPropertyRequest.SerializeToString,
            SiLA2Common__pb2.PropertyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
