# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import PlateReaderService_pb2 as PlateReaderService__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in PlateReaderService_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PlateReaderServiceStub(object):
    """═══════════════════════════════════════════════════════════════════════════
    SERVICE DEFINITION
    ═══════════════════════════════════════════════════════════════════════════

    ─── Properties ────────────────────────────────────────────────────────
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetIsConnected = channel.unary_unary(
                '/it.chemlab.platereader.PlateReaderService/GetIsConnected',
                request_serializer=PlateReaderService__pb2.GetIsConnectedRequest.SerializeToString,
                response_deserializer=PlateReaderService__pb2.GetIsConnectedResponse.FromString,
                _registered_method=True)
        self.SubscribeIsConnected = channel.unary_stream(
                '/it.chemlab.platereader.PlateReaderService/SubscribeIsConnected',
                request_serializer=PlateReaderService__pb2.SubscribeIsConnectedRequest.SerializeToString,
                response_deserializer=PlateReaderService__pb2.GetIsConnectedResponse.FromString,
                _registered_method=True)
        self.GetOperationalStatus = channel.unary_unary(
                '/it.chemlab.platereader.PlateReaderService/GetOperationalStatus',
                request_serializer=PlateReaderService__pb2.GetOperationalStatusRequest.SerializeToString,
                response_deserializer=PlateReaderService__pb2.GetOperationalStatusResponse.FromString,
                _registered_method=True)
        self.SubscribeOperationalStatus = channel.unary_stream(
                '/it.chemlab.platereader.PlateReaderService/SubscribeOperationalStatus',
                request_serializer=PlateReaderService__pb2.SubscribeOperationalStatusRequest.SerializeToString,
                response_deserializer=PlateReaderService__pb2.GetOperationalStatusResponse.FromString,
                _registered_method=True)
        self.GetCurrentTemperature = channel.unary_unary(
                '/it.chemlab.platereader.PlateReaderService/GetCurrentTemperature',
                request_serializer=PlateReaderService__pb2.GetCurrentTemperatureRequest.SerializeToString,
                response_deserializer=PlateReaderService__pb2.GetCurrentTemperatureResponse.FromString,
                _registered_method=True)
        self.SubscribeCurrentTemperature = channel.unary_stream(
                '/it.chemlab.platereader.PlateReaderService/SubscribeCurrentTemperature',
                request_serializer=PlateReaderService__pb2.SubscribeCurrentTemperatureRequest.SerializeToString,
                response_deserializer=PlateReaderService__pb2.GetCurrentTemperatureResponse.FromString,
                _registered_method=True)
        self.GetInstrumentInfo = channel.unary_unary(
                '/it.chemlab.platereader.PlateReaderService/GetInstrumentInfo',
                request_serializer=PlateReaderService__pb2.GetInstrumentInfoRequest.SerializeToString,
                response_deserializer=PlateReaderService__pb2.GetInstrumentInfoResponse.FromString,
                _registered_method=True)
        self.Connect = channel.unary_unary(
                '/it.chemlab.platereader.PlateReaderService/Connect',
                request_serializer=PlateReaderService__pb2.ConnectRequest.SerializeToString,
                response_deserializer=PlateReaderService__pb2.ConnectResponse.FromString,
                _registered_method=True)
        self.Disconnect = channel.unary_unary(
                '/it.chemlab.platereader.PlateReaderService/Disconnect',
                request_serializer=PlateReaderService__pb2.DisconnectRequest.SerializeToString,
                response_deserializer=PlateReaderService__pb2.DisconnectResponse.FromString,
                _registered_method=True)
        self.PlateIn = channel.unary_unary(
                '/it.chemlab.platereader.PlateReaderService/PlateIn',
                request_serializer=PlateReaderService__pb2.PlateInRequest.SerializeToString,
                response_deserializer=PlateReaderService__pb2.PlateInResponse.FromString,
                _registered_method=True)
        self.PlateOut = channel.unary_unary(
                '/it.chemlab.platereader.PlateReaderService/PlateOut',
                request_serializer=PlateReaderService__pb2.PlateOutRequest.SerializeToString,
                response_deserializer=PlateReaderService__pb2.PlateOutResponse.FromString,
                _registered_method=True)
        self.SetTemperature = channel.unary_unary(
                '/it.chemlab.platereader.PlateReaderService/SetTemperature',
                request_serializer=PlateReaderService__pb2.SetTemperatureRequest.SerializeToString,
                response_deserializer=PlateReaderService__pb2.SetTemperatureResponse.FromString,
                _registered_method=True)
        self.TurnOffTemperature = channel.unary_unary(
                '/it.chemlab.platereader.PlateReaderService/TurnOffTemperature',
                request_serializer=PlateReaderService__pb2.TurnOffTemperatureRequest.SerializeToString,
                response_deserializer=PlateReaderService__pb2.TurnOffTemperatureResponse.FromString,
                _registered_method=True)
        self.RunMeasurement = channel.unary_stream(
                '/it.chemlab.platereader.PlateReaderService/RunMeasurement',
                request_serializer=PlateReaderService__pb2.RunMeasurementRequest.SerializeToString,
                response_deserializer=PlateReaderService__pb2.RunMeasurementResponse.FromString,
                _registered_method=True)
        self.GetAnIMLResult = channel.unary_unary(
                '/it.chemlab.platereader.PlateReaderService/GetAnIMLResult',
                request_serializer=PlateReaderService__pb2.GetAnIMLResultRequest.SerializeToString,
                response_deserializer=PlateReaderService__pb2.GetAnIMLResultResponse.FromString,
                _registered_method=True)
        self.ListProtocols = channel.unary_unary(
                '/it.chemlab.platereader.PlateReaderService/ListProtocols',
                request_serializer=PlateReaderService__pb2.ListProtocolsRequest.SerializeToString,
                response_deserializer=PlateReaderService__pb2.ListProtocolsResponse.FromString,
                _registered_method=True)


class PlateReaderServiceServicer(object):
    """═══════════════════════════════════════════════════════════════════════════
    SERVICE DEFINITION
    ═══════════════════════════════════════════════════════════════════════════

    ─── Properties ────────────────────────────────────────────────────────
    """

    def GetIsConnected(self, request, context):
        """IsConnected (Observable)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeIsConnected(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOperationalStatus(self, request, context):
        """OperationalStatus (Observable)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeOperationalStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCurrentTemperature(self, request, context):
        """CurrentTemperature (Observable)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeCurrentTemperature(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInstrumentInfo(self, request, context):
        """InstrumentInfo (Non-Observable)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Connect(self, request, context):
        """─── Commands ──────────────────────────────────────────────────────────

        Connect
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Disconnect(self, request, context):
        """Disconnect
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlateIn(self, request, context):
        """PlateIn
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlateOut(self, request, context):
        """PlateOut
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetTemperature(self, request, context):
        """SetTemperature
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TurnOffTemperature(self, request, context):
        """TurnOffTemperature
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunMeasurement(self, request, context):
        """RunMeasurement (Observable/Streaming - Long Running)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAnIMLResult(self, request, context):
        """GetAnIMLResult
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListProtocols(self, request, context):
        """ListProtocols
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PlateReaderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetIsConnected': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIsConnected,
                    request_deserializer=PlateReaderService__pb2.GetIsConnectedRequest.FromString,
                    response_serializer=PlateReaderService__pb2.GetIsConnectedResponse.SerializeToString,
            ),
            'SubscribeIsConnected': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeIsConnected,
                    request_deserializer=PlateReaderService__pb2.SubscribeIsConnectedRequest.FromString,
                    response_serializer=PlateReaderService__pb2.GetIsConnectedResponse.SerializeToString,
            ),
            'GetOperationalStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOperationalStatus,
                    request_deserializer=PlateReaderService__pb2.GetOperationalStatusRequest.FromString,
                    response_serializer=PlateReaderService__pb2.GetOperationalStatusResponse.SerializeToString,
            ),
            'SubscribeOperationalStatus': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeOperationalStatus,
                    request_deserializer=PlateReaderService__pb2.SubscribeOperationalStatusRequest.FromString,
                    response_serializer=PlateReaderService__pb2.GetOperationalStatusResponse.SerializeToString,
            ),
            'GetCurrentTemperature': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCurrentTemperature,
                    request_deserializer=PlateReaderService__pb2.GetCurrentTemperatureRequest.FromString,
                    response_serializer=PlateReaderService__pb2.GetCurrentTemperatureResponse.SerializeToString,
            ),
            'SubscribeCurrentTemperature': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeCurrentTemperature,
                    request_deserializer=PlateReaderService__pb2.SubscribeCurrentTemperatureRequest.FromString,
                    response_serializer=PlateReaderService__pb2.GetCurrentTemperatureResponse.SerializeToString,
            ),
            'GetInstrumentInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInstrumentInfo,
                    request_deserializer=PlateReaderService__pb2.GetInstrumentInfoRequest.FromString,
                    response_serializer=PlateReaderService__pb2.GetInstrumentInfoResponse.SerializeToString,
            ),
            'Connect': grpc.unary_unary_rpc_method_handler(
                    servicer.Connect,
                    request_deserializer=PlateReaderService__pb2.ConnectRequest.FromString,
                    response_serializer=PlateReaderService__pb2.ConnectResponse.SerializeToString,
            ),
            'Disconnect': grpc.unary_unary_rpc_method_handler(
                    servicer.Disconnect,
                    request_deserializer=PlateReaderService__pb2.DisconnectRequest.FromString,
                    response_serializer=PlateReaderService__pb2.DisconnectResponse.SerializeToString,
            ),
            'PlateIn': grpc.unary_unary_rpc_method_handler(
                    servicer.PlateIn,
                    request_deserializer=PlateReaderService__pb2.PlateInRequest.FromString,
                    response_serializer=PlateReaderService__pb2.PlateInResponse.SerializeToString,
            ),
            'PlateOut': grpc.unary_unary_rpc_method_handler(
                    servicer.PlateOut,
                    request_deserializer=PlateReaderService__pb2.PlateOutRequest.FromString,
                    response_serializer=PlateReaderService__pb2.PlateOutResponse.SerializeToString,
            ),
            'SetTemperature': grpc.unary_unary_rpc_method_handler(
                    servicer.SetTemperature,
                    request_deserializer=PlateReaderService__pb2.SetTemperatureRequest.FromString,
                    response_serializer=PlateReaderService__pb2.SetTemperatureResponse.SerializeToString,
            ),
            'TurnOffTemperature': grpc.unary_unary_rpc_method_handler(
                    servicer.TurnOffTemperature,
                    request_deserializer=PlateReaderService__pb2.TurnOffTemperatureRequest.FromString,
                    response_serializer=PlateReaderService__pb2.TurnOffTemperatureResponse.SerializeToString,
            ),
            'RunMeasurement': grpc.unary_stream_rpc_method_handler(
                    servicer.RunMeasurement,
                    request_deserializer=PlateReaderService__pb2.RunMeasurementRequest.FromString,
                    response_serializer=PlateReaderService__pb2.RunMeasurementResponse.SerializeToString,
            ),
            'GetAnIMLResult': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAnIMLResult,
                    request_deserializer=PlateReaderService__pb2.GetAnIMLResultRequest.FromString,
                    response_serializer=PlateReaderService__pb2.GetAnIMLResultResponse.SerializeToString,
            ),
            'ListProtocols': grpc.unary_unary_rpc_method_handler(
                    servicer.ListProtocols,
                    request_deserializer=PlateReaderService__pb2.ListProtocolsRequest.FromString,
                    response_serializer=PlateReaderService__pb2.ListProtocolsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'it.chemlab.platereader.PlateReaderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('it.chemlab.platereader.PlateReaderService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PlateReaderService(object):
    """═══════════════════════════════════════════════════════════════════════════
    SERVICE DEFINITION
    ═══════════════════════════════════════════════════════════════════════════

    ─── Properties ────────────────────────────────────────────────────────
    """

    @staticmethod
    def GetIsConnected(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/it.chemlab.platereader.PlateReaderService/GetIsConnected',
            PlateReaderService__pb2.GetIsConnectedRequest.SerializeToString,
            PlateReaderService__pb2.GetIsConnectedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeIsConnected(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/it.chemlab.platereader.PlateReaderService/SubscribeIsConnected',
            PlateReaderService__pb2.SubscribeIsConnectedRequest.SerializeToString,
            PlateReaderService__pb2.GetIsConnectedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOperationalStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/it.chemlab.platereader.PlateReaderService/GetOperationalStatus',
            PlateReaderService__pb2.GetOperationalStatusRequest.SerializeToString,
            PlateReaderService__pb2.GetOperationalStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeOperationalStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/it.chemlab.platereader.PlateReaderService/SubscribeOperationalStatus',
            PlateReaderService__pb2.SubscribeOperationalStatusRequest.SerializeToString,
            PlateReaderService__pb2.GetOperationalStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCurrentTemperature(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/it.chemlab.platereader.PlateReaderService/GetCurrentTemperature',
            PlateReaderService__pb2.GetCurrentTemperatureRequest.SerializeToString,
            PlateReaderService__pb2.GetCurrentTemperatureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeCurrentTemperature(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/it.chemlab.platereader.PlateReaderService/SubscribeCurrentTemperature',
            PlateReaderService__pb2.SubscribeCurrentTemperatureRequest.SerializeToString,
            PlateReaderService__pb2.GetCurrentTemperatureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetInstrumentInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/it.chemlab.platereader.PlateReaderService/GetInstrumentInfo',
            PlateReaderService__pb2.GetInstrumentInfoRequest.SerializeToString,
            PlateReaderService__pb2.GetInstrumentInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Connect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/it.chemlab.platereader.PlateReaderService/Connect',
            PlateReaderService__pb2.ConnectRequest.SerializeToString,
            PlateReaderService__pb2.ConnectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Disconnect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/it.chemlab.platereader.PlateReaderService/Disconnect',
            PlateReaderService__pb2.DisconnectRequest.SerializeToString,
            PlateReaderService__pb2.DisconnectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PlateIn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/it.chemlab.platereader.PlateReaderService/PlateIn',
            PlateReaderService__pb2.PlateInRequest.SerializeToString,
            PlateReaderService__pb2.PlateInResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PlateOut(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/it.chemlab.platereader.PlateReaderService/PlateOut',
            PlateReaderService__pb2.PlateOutRequest.SerializeToString,
            PlateReaderService__pb2.PlateOutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetTemperature(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/it.chemlab.platereader.PlateReaderService/SetTemperature',
            PlateReaderService__pb2.SetTemperatureRequest.SerializeToString,
            PlateReaderService__pb2.SetTemperatureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TurnOffTemperature(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/it.chemlab.platereader.PlateReaderService/TurnOffTemperature',
            PlateReaderService__pb2.TurnOffTemperatureRequest.SerializeToString,
            PlateReaderService__pb2.TurnOffTemperatureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunMeasurement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/it.chemlab.platereader.PlateReaderService/RunMeasurement',
            PlateReaderService__pb2.RunMeasurementRequest.SerializeToString,
            PlateReaderService__pb2.RunMeasurementResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAnIMLResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/it.chemlab.platereader.PlateReaderService/GetAnIMLResult',
            PlateReaderService__pb2.GetAnIMLResultRequest.SerializeToString,
            PlateReaderService__pb2.GetAnIMLResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListProtocols(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/it.chemlab.platereader.PlateReaderService/ListProtocols',
            PlateReaderService__pb2.ListProtocolsRequest.SerializeToString,
            PlateReaderService__pb2.ListProtocolsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
