# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import TaskManagement_pb2 as TaskManagement__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in TaskManagement_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TaskManagementStub(object):
    """═══════════════════════════════════════════════════════════════════════════
    SERVICE DEFINITION
    ═══════════════════════════════════════════════════════════════════════════

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Get_AvailableTasks = channel.unary_unary(
                '/sila2.it.bicoccalab.taskmanagement.v1.TaskManagement/Get_AvailableTasks',
                request_serializer=TaskManagement__pb2.Get_AvailableTasks_Request.SerializeToString,
                response_deserializer=TaskManagement__pb2.Get_AvailableTasks_Response.FromString,
                _registered_method=True)
        self.Get_CurrentTaskId = channel.unary_unary(
                '/sila2.it.bicoccalab.taskmanagement.v1.TaskManagement/Get_CurrentTaskId',
                request_serializer=TaskManagement__pb2.Get_CurrentTaskId_Request.SerializeToString,
                response_deserializer=TaskManagement__pb2.Get_CurrentTaskId_Response.FromString,
                _registered_method=True)
        self.Get_CurrentSubtask = channel.unary_unary(
                '/sila2.it.bicoccalab.taskmanagement.v1.TaskManagement/Get_CurrentSubtask',
                request_serializer=TaskManagement__pb2.Get_CurrentSubtask_Request.SerializeToString,
                response_deserializer=TaskManagement__pb2.Get_CurrentSubtask_Response.FromString,
                _registered_method=True)
        self.Get_TaskStatus = channel.unary_unary(
                '/sila2.it.bicoccalab.taskmanagement.v1.TaskManagement/Get_TaskStatus',
                request_serializer=TaskManagement__pb2.Get_TaskStatus_Request.SerializeToString,
                response_deserializer=TaskManagement__pb2.Get_TaskStatus_Response.FromString,
                _registered_method=True)
        self.Get_RobotConnectionStatus = channel.unary_unary(
                '/sila2.it.bicoccalab.taskmanagement.v1.TaskManagement/Get_RobotConnectionStatus',
                request_serializer=TaskManagement__pb2.Get_RobotConnectionStatus_Request.SerializeToString,
                response_deserializer=TaskManagement__pb2.Get_RobotConnectionStatus_Response.FromString,
                _registered_method=True)
        self.RefreshTasks = channel.unary_unary(
                '/sila2.it.bicoccalab.taskmanagement.v1.TaskManagement/RefreshTasks',
                request_serializer=TaskManagement__pb2.RefreshTasks_Request.SerializeToString,
                response_deserializer=TaskManagement__pb2.RefreshTasks_Response.FromString,
                _registered_method=True)
        self.ExecuteTask = channel.unary_stream(
                '/sila2.it.bicoccalab.taskmanagement.v1.TaskManagement/ExecuteTask',
                request_serializer=TaskManagement__pb2.ExecuteTask_Request.SerializeToString,
                response_deserializer=TaskManagement__pb2.ExecuteTask_Response.FromString,
                _registered_method=True)
        self.CancelTask = channel.unary_unary(
                '/sila2.it.bicoccalab.taskmanagement.v1.TaskManagement/CancelTask',
                request_serializer=TaskManagement__pb2.CancelTask_Request.SerializeToString,
                response_deserializer=TaskManagement__pb2.CancelTask_Response.FromString,
                _registered_method=True)
        self.GetTaskDetails = channel.unary_unary(
                '/sila2.it.bicoccalab.taskmanagement.v1.TaskManagement/GetTaskDetails',
                request_serializer=TaskManagement__pb2.GetTaskDetails_Request.SerializeToString,
                response_deserializer=TaskManagement__pb2.GetTaskDetails_Response.FromString,
                _registered_method=True)
        self.ConnectToRobot = channel.unary_unary(
                '/sila2.it.bicoccalab.taskmanagement.v1.TaskManagement/ConnectToRobot',
                request_serializer=TaskManagement__pb2.ConnectToRobot_Request.SerializeToString,
                response_deserializer=TaskManagement__pb2.ConnectToRobot_Response.FromString,
                _registered_method=True)


class TaskManagementServicer(object):
    """═══════════════════════════════════════════════════════════════════════════
    SERVICE DEFINITION
    ═══════════════════════════════════════════════════════════════════════════

    """

    def Get_AvailableTasks(self, request, context):
        """Properties
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get_CurrentTaskId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get_CurrentSubtask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get_TaskStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get_RobotConnectionStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefreshTasks(self, request, context):
        """Commands
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteTask(self, request, context):
        """Streaming for progress
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTaskDetails(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConnectToRobot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TaskManagementServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Get_AvailableTasks': grpc.unary_unary_rpc_method_handler(
                    servicer.Get_AvailableTasks,
                    request_deserializer=TaskManagement__pb2.Get_AvailableTasks_Request.FromString,
                    response_serializer=TaskManagement__pb2.Get_AvailableTasks_Response.SerializeToString,
            ),
            'Get_CurrentTaskId': grpc.unary_unary_rpc_method_handler(
                    servicer.Get_CurrentTaskId,
                    request_deserializer=TaskManagement__pb2.Get_CurrentTaskId_Request.FromString,
                    response_serializer=TaskManagement__pb2.Get_CurrentTaskId_Response.SerializeToString,
            ),
            'Get_CurrentSubtask': grpc.unary_unary_rpc_method_handler(
                    servicer.Get_CurrentSubtask,
                    request_deserializer=TaskManagement__pb2.Get_CurrentSubtask_Request.FromString,
                    response_serializer=TaskManagement__pb2.Get_CurrentSubtask_Response.SerializeToString,
            ),
            'Get_TaskStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.Get_TaskStatus,
                    request_deserializer=TaskManagement__pb2.Get_TaskStatus_Request.FromString,
                    response_serializer=TaskManagement__pb2.Get_TaskStatus_Response.SerializeToString,
            ),
            'Get_RobotConnectionStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.Get_RobotConnectionStatus,
                    request_deserializer=TaskManagement__pb2.Get_RobotConnectionStatus_Request.FromString,
                    response_serializer=TaskManagement__pb2.Get_RobotConnectionStatus_Response.SerializeToString,
            ),
            'RefreshTasks': grpc.unary_unary_rpc_method_handler(
                    servicer.RefreshTasks,
                    request_deserializer=TaskManagement__pb2.RefreshTasks_Request.FromString,
                    response_serializer=TaskManagement__pb2.RefreshTasks_Response.SerializeToString,
            ),
            'ExecuteTask': grpc.unary_stream_rpc_method_handler(
                    servicer.ExecuteTask,
                    request_deserializer=TaskManagement__pb2.ExecuteTask_Request.FromString,
                    response_serializer=TaskManagement__pb2.ExecuteTask_Response.SerializeToString,
            ),
            'CancelTask': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelTask,
                    request_deserializer=TaskManagement__pb2.CancelTask_Request.FromString,
                    response_serializer=TaskManagement__pb2.CancelTask_Response.SerializeToString,
            ),
            'GetTaskDetails': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTaskDetails,
                    request_deserializer=TaskManagement__pb2.GetTaskDetails_Request.FromString,
                    response_serializer=TaskManagement__pb2.GetTaskDetails_Response.SerializeToString,
            ),
            'ConnectToRobot': grpc.unary_unary_rpc_method_handler(
                    servicer.ConnectToRobot,
                    request_deserializer=TaskManagement__pb2.ConnectToRobot_Request.FromString,
                    response_serializer=TaskManagement__pb2.ConnectToRobot_Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sila2.it.bicoccalab.taskmanagement.v1.TaskManagement', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sila2.it.bicoccalab.taskmanagement.v1.TaskManagement', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TaskManagement(object):
    """═══════════════════════════════════════════════════════════════════════════
    SERVICE DEFINITION
    ═══════════════════════════════════════════════════════════════════════════

    """

    @staticmethod
    def Get_AvailableTasks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sila2.it.bicoccalab.taskmanagement.v1.TaskManagement/Get_AvailableTasks',
            TaskManagement__pb2.Get_AvailableTasks_Request.SerializeToString,
            TaskManagement__pb2.Get_AvailableTasks_Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get_CurrentTaskId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sila2.it.bicoccalab.taskmanagement.v1.TaskManagement/Get_CurrentTaskId',
            TaskManagement__pb2.Get_CurrentTaskId_Request.SerializeToString,
            TaskManagement__pb2.Get_CurrentTaskId_Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get_CurrentSubtask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sila2.it.bicoccalab.taskmanagement.v1.TaskManagement/Get_CurrentSubtask',
            TaskManagement__pb2.Get_CurrentSubtask_Request.SerializeToString,
            TaskManagement__pb2.Get_CurrentSubtask_Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get_TaskStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sila2.it.bicoccalab.taskmanagement.v1.TaskManagement/Get_TaskStatus',
            TaskManagement__pb2.Get_TaskStatus_Request.SerializeToString,
            TaskManagement__pb2.Get_TaskStatus_Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get_RobotConnectionStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sila2.it.bicoccalab.taskmanagement.v1.TaskManagement/Get_RobotConnectionStatus',
            TaskManagement__pb2.Get_RobotConnectionStatus_Request.SerializeToString,
            TaskManagement__pb2.Get_RobotConnectionStatus_Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RefreshTasks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sila2.it.bicoccalab.taskmanagement.v1.TaskManagement/RefreshTasks',
            TaskManagement__pb2.RefreshTasks_Request.SerializeToString,
            TaskManagement__pb2.RefreshTasks_Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/sila2.it.bicoccalab.taskmanagement.v1.TaskManagement/ExecuteTask',
            TaskManagement__pb2.ExecuteTask_Request.SerializeToString,
            TaskManagement__pb2.ExecuteTask_Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sila2.it.bicoccalab.taskmanagement.v1.TaskManagement/CancelTask',
            TaskManagement__pb2.CancelTask_Request.SerializeToString,
            TaskManagement__pb2.CancelTask_Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTaskDetails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sila2.it.bicoccalab.taskmanagement.v1.TaskManagement/GetTaskDetails',
            TaskManagement__pb2.GetTaskDetails_Request.SerializeToString,
            TaskManagement__pb2.GetTaskDetails_Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConnectToRobot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sila2.it.bicoccalab.taskmanagement.v1.TaskManagement/ConnectToRobot',
            TaskManagement__pb2.ConnectToRobot_Request.SerializeToString,
            TaskManagement__pb2.ConnectToRobot_Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
